---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClusterInstanceClass
metadata:
  name: postgres
spec:
  description:
    short: tanzu-postgres-databases
  pool:
    group: sql.tanzu.vmware.com
    kind: Postgres