apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: locations-routes-config
spec:
  service: 
    name: locations-brownfield-proxy
  routes:
    - predicates:
        - Path=/list-locations
        - Method=GET
      ssoEnabled: true
    - predicates:
        - Path=/process-donation/*/adoption-request/**
        - Method=POST
      ssoEnabled: true
      filters:
      - CircuitBreaker="locationsCircuitBreaker,forward:/alternate-donation-service"
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: locations-gateway
spec:
  count: 1
  api:
    serverUrl: http://locations.brownfield.dekt.io
    title: GEO-Location Services
    description: APIs to help with geo-locations and physical branches
    version: 0.5.0
    cors:
      allowedOrigins:
      - http://api-portal.sys.dekt.io
---
apiVersion: v1
kind: Service
metadata:
  name: locations-brownfield-proxy
spec:
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: locations-routes-mapping
spec:
  gatewayRef:
    name: locations-gateway
  routeConfigRef:
    name: locations-routes-config