apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: mood-portal
  labels:
    apps.tanzu.vmware.com/workload-type: dekt-url
    app.kubernetes.io/part-of: mood-portal
spec:
  source:
    git:
      url: https://github.com/dektlong/mood-portal
      ref:
        branch: main
  env:
    - name: HAPPY_THRESHOLD
      value: UPDATED_IN_RUNTIME
    - name: SENSORS_ACTIVATE_API
      value: UPDATED_IN_RUNTIME
    - name: SENSORS_MEASURE_API
      value: UPDATED_IN_RUNTIME
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"