openapi: 3.0.1
servers:
  - url: http://mood-sensors.dev.CHANGE_ME
  - url: http://mood-sensors.prod.CHANGE_ME
info:
  title: API definition for mood-sensors
  version: 0.0.8
tags:
  - name: "contorl-sensors"
    description: "Contorl sensors operation"
  - name: "collect-data"
    description: "Collect data from sensors"
paths:
  /activate{sensor_id}:
    post:
      tags:
      - "contorl-sensors"
      description: "activate a sensor"
      parameters:
      - name: "sensor_id"
        in: path
        description: "the sensor identifier"
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "successful sensor activation"
        "400":
          description: "error activating sensor"
  /activate:
    post:
      tags:
      - "contorl-sensors"
      description: "activate all available sensors"
      responses:
        "200":
          description: "successful sensors activation"
        "400":
          description: "error activating sensors"
  /measure/{sensor_id}:
    get:
      tags:
      - "collect-data"
      description: "measure mood status from a sensor"
      parameters:
      - name: "sensor_id"
        in: path
        description: "the sensor identifier"
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "successful sensor data collection"
        "400":
          description: "error collecting data from sensor"
  /measure:
    get:
      tags:
      - "collect-data"
      description: "measure mood status from all sensor"
      responses:
        200:
          description: "A paged array of all sensors data"
          headers:
            x-next:
              description: "A link to the next page of responses"
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sensors"
        default:
          description: "error collecting data from sensors"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Sensor:
      type: object
      required:
        - id
        - team
        - mood
      properties:
        id:
          type: integer
          format: int64
        team:
          type: string
        mood:
          type: string
    Sensors:
      type: array
      items:
        $ref: "#/components/schemas/Sensor"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string