apiVersion: carto.run/v1alpha1
kind: ClusterImageTemplate
metadata:
  name: image-scanner-template
spec:
  imagePath: ".status.compliantArtifact.registry.image"
  ytt: |
    #@ load("@ytt:data", "data")
    apiVersion: scanning.apps.tanzu.vmware.com/v1beta1
    kind: ImageScan
    metadata:
      name: #@ data.values.workload.metadata.name
      labels:
        app.kubernetes.io/component: image-scan
        #@ if/end hasattr(data.values.workload.metadata, "labels") and hasattr(data.values.workload.metadata.labels, "app.kubernetes.io/part-of"):
        app.kubernetes.io/part-of: #@ data.values.workload.metadata.labels["app.kubernetes.io/part-of"]
    spec:
      registry:
        image: #@ data.values.image
      scanTemplate: private-image-scan-template
      scanPolicy: scan-policy

