apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-sensors
  labels:
    apps.tanzu.vmware.com/workload-type: stream
spec:
  source:
    git:
      url: https://github.com/tanzu-end-to-end/spring-sensors-sensor
      ref:
        branch: main
  serviceClaims:
    - name: rmq
      ref:
        apiVersion: rabbitmq.com/v1beta1
        kind: RabbitmqCluster
        name: sensors-queue