apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: dekt4pets-gateway-dev
spec:
  api:
    serverUrl: http://dekt4pets-dev.tanzu.dekt.io 
    title: "Dekt4pets-dev"
    description: "Micro Gateway to control internal APIs for developing the dekt4pets online store"
    version: "1.0.0-K8s"
    cors:
      allowedOrigins:
      - "http://api-portal.tanzu.dekt.io"
  count: 1
  sso:
    secret: sso-secret