apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: devx-mood
  labels:
    apps.tanzu.vmware.com/workload-type: web
spec:
  source:
    git:
      url: https://github.com/dektlong/devx-mood
      ref:
        branch: main
